# Generated by Django 4.1.7 on 2023-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('interiors', 'interiors'), ('furniture', 'furniture'), ('installation', 'installation')], default='interiors', max_length=14),
        ),
    ]
