# Generated by Django 4.1.7 on 2023-04-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_image_projects_image1_projects_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image1',
            field=models.ImageField(default='1.jpg', upload_to='projectsImage'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image2',
            field=models.ImageField(default='1.jpg', upload_to='projectsImage'),
        ),
    ]
