# Generated by Django 4.1.7 on 2023-04-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_projects_image1_alter_projects_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
