# Generated by Django 4.1.7 on 2023-04-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
