# Generated by Django 4.1.7 on 2023-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('interiors', 'interiors'), ('furniture', 'furniture'), ('installation', 'installation')], default='interiors', max_length=14)),
                ('image1', models.ImageField(upload_to='projectsImage')),
                ('image2', models.ImageField(upload_to='projectsImage')),
            ],
        ),
    ]
